// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChunkText(arg1) {
  return window['go']['main']['App']['ChunkText'](arg1);
}

export function CreateFile(arg1, arg2) {
  return window['go']['main']['App']['CreateFile'](arg1, arg2);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function FindSimilar(arg1, arg2) {
  return window['go']['main']['App']['FindSimilar'](arg1, arg2);
}

export function GenerateEmbedding(arg1) {
  return window['go']['main']['App']['GenerateEmbedding'](arg1);
}

export function GenerateEmbeddingsBatch(arg1) {
  return window['go']['main']['App']['GenerateEmbeddingsBatch'](arg1);
}

export function GetAIStatus() {
  return window['go']['main']['App']['GetAIStatus']();
}

export function GetBasePath() {
  return window['go']['main']['App']['GetBasePath']();
}

export function GetChunkingConfig() {
  return window['go']['main']['App']['GetChunkingConfig']();
}

export function GetDatabaseStats() {
  return window['go']['main']['App']['GetDatabaseStats']();
}

export function GetGraphConfig() {
  return window['go']['main']['App']['GetGraphConfig']();
}

export function GetGraphData() {
  return window['go']['main']['App']['GetGraphData']();
}

export function GetIndexedFile(arg1) {
  return window['go']['main']['App']['GetIndexedFile'](arg1);
}

export function GetLLMConfig() {
  return window['go']['main']['App']['GetLLMConfig']();
}

export function GetOllamaConfig() {
  return window['go']['main']['App']['GetOllamaConfig']();
}

export function GetOpenAIConfig() {
  return window['go']['main']['App']['GetOpenAIConfig']();
}

export function GetRAGConfig() {
  return window['go']['main']['App']['GetRAGConfig']();
}

export function GetRAGStatus() {
  return window['go']['main']['App']['GetRAGStatus']();
}

export function GetSimilarityStatus() {
  return window['go']['main']['App']['GetSimilarityStatus']();
}

export function IndexFile(arg1) {
  return window['go']['main']['App']['IndexFile'](arg1);
}

export function IndexFileWithEmbedding(arg1) {
  return window['go']['main']['App']['IndexFileWithEmbedding'](arg1);
}

export function IsDatabaseInitialized() {
  return window['go']['main']['App']['IsDatabaseInitialized']();
}

export function ListFiles() {
  return window['go']['main']['App']['ListFiles']();
}

export function ListIndexedFiles() {
  return window['go']['main']['App']['ListIndexedFiles']();
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function ProcessDocument(arg1) {
  return window['go']['main']['App']['ProcessDocument'](arg1);
}

export function RAGQuery(arg1) {
  return window['go']['main']['App']['RAGQuery'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReindexAllWithEmbeddings() {
  return window['go']['main']['App']['ReindexAllWithEmbeddings']();
}

export function RemoveFromIndex(arg1) {
  return window['go']['main']['App']['RemoveFromIndex'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SetAIModel(arg1) {
  return window['go']['main']['App']['SetAIModel'](arg1);
}

export function SetAIProvider(arg1) {
  return window['go']['main']['App']['SetAIProvider'](arg1);
}

export function SetChunkingConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SetChunkingConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SetFolder(arg1) {
  return window['go']['main']['App']['SetFolder'](arg1);
}

export function SetGraphConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetGraphConfig'](arg1, arg2, arg3);
}

export function SetLLMConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SetLLMConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SetOllamaConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetOllamaConfig'](arg1, arg2, arg3);
}

export function SetOpenAIConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetOpenAIConfig'](arg1, arg2, arg3);
}

export function SetRAGConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetRAGConfig'](arg1, arg2, arg3);
}

export function TestOpenAIConnection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestOpenAIConnection'](arg1, arg2, arg3, arg4);
}

export function UpdateFilePathInIndex(arg1, arg2) {
  return window['go']['main']['App']['UpdateFilePathInIndex'](arg1, arg2);
}
