// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {files} from '../models';

export function CreateFile(arg1:string,arg2:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function GetBasePath():Promise<string>;

export function GetDatabaseStats():Promise<Record<string, any>>;

export function GetIndexedFile(arg1:string):Promise<database.File>;

export function IndexFile(arg1:string):Promise<void>;

export function IsDatabaseInitialized():Promise<boolean>;

export function ListFiles():Promise<files.FileNode>;

export function ListIndexedFiles():Promise<Array<database.File>>;

export function OpenFolder():Promise<string>;

export function ReadFile(arg1:string):Promise<files.NoteContent>;

export function RemoveFromIndex(arg1:string):Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SetFolder(arg1:string):Promise<void>;

export function UpdateFilePathInIndex(arg1:string,arg2:string):Promise<void>;
