// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFile(arg1, arg2) {
  return window['go']['main']['App']['CreateFile'](arg1, arg2);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function GetBasePath() {
  return window['go']['main']['App']['GetBasePath']();
}

export function ListFiles() {
  return window['go']['main']['App']['ListFiles']();
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SetFolder(arg1) {
  return window['go']['main']['App']['SetFolder'](arg1);
}
