// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';
import {graph} from '../models';
import {database} from '../models';
import {files} from '../models';

export function ChunkText(arg1:string):Promise<Array<Record<string, any>>>;

export function CreateFile(arg1:string,arg2:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function FindSimilar(arg1:string,arg2:number):Promise<Array<main.SimilarNote>>;

export function GenerateEmbedding(arg1:string):Promise<Array<number>>;

export function GenerateEmbeddingsBatch(arg1:Array<string>):Promise<Array<any>>;

export function GetAIStatus():Promise<Record<string, any>>;

export function GetBasePath():Promise<string>;

export function GetChunkingConfig():Promise<config.ChunkingConfig>;

export function GetDatabaseStats():Promise<Record<string, any>>;

export function GetGraphConfig():Promise<config.GraphConfig>;

export function GetGraphData():Promise<graph.GraphData>;

export function GetIndexedFile(arg1:string):Promise<database.File>;

export function GetLLMConfig():Promise<config.LLMConfig>;

export function GetOllamaConfig():Promise<config.OllamaConfig>;

export function GetOpenAIConfig():Promise<config.OpenAIConfig>;

export function GetRAGConfig():Promise<config.RAGConfig>;

export function GetRAGStatus():Promise<Record<string, any>>;

export function GetSimilarityStatus():Promise<Record<string, any>>;

export function IndexFile(arg1:string):Promise<void>;

export function IndexFileWithEmbedding(arg1:string):Promise<void>;

export function IsDatabaseInitialized():Promise<boolean>;

export function ListFiles():Promise<files.FileNode>;

export function ListIndexedFiles():Promise<Array<database.File>>;

export function OpenFolder():Promise<string>;

export function ProcessDocument(arg1:string):Promise<Array<Record<string, any>>>;

export function RAGQuery(arg1:string):Promise<Record<string, any>>;

export function ReadFile(arg1:string):Promise<files.NoteContent>;

export function ReindexAllWithEmbeddings():Promise<Record<string, any>>;

export function RemoveFromIndex(arg1:string):Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SetAIModel(arg1:string):Promise<void>;

export function SetAIProvider(arg1:string):Promise<void>;

export function SetChunkingConfig(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number,arg6:boolean,arg7:string):Promise<void>;

export function SetFolder(arg1:string):Promise<void>;

export function SetGraphConfig(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function SetLLMConfig(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function SetOllamaConfig(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SetOpenAIConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetRAGConfig(arg1:number,arg2:number,arg3:string):Promise<void>;

export function TestOpenAIConnection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function UpdateFilePathInIndex(arg1:string,arg2:string):Promise<void>;
