// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {files} from '../models';

export function CreateFile(arg1:string,arg2:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function GetBasePath():Promise<string>;

export function ListFiles():Promise<files.FileNode>;

export function OpenFolder():Promise<string>;

export function ReadFile(arg1:string):Promise<files.NoteContent>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SetFolder(arg1:string):Promise<void>;
